# Generated by Django 4.1.1 on 2022-11-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildings",
            name="image",
        ),
        migrations.AddField(
            model_name="buildings",
            name="subject",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="location",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
