# Generated by Django 4.1.1 on 2022-11-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_remove_buildings_image_buildings_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildings",
            name="date",
            field=models.DateTimeField(
                choices=[
                    ("12-11-22", "12-11-22"),
                    ("13-11-22", "13-11-22"),
                    ("14-11-22", "14-11-22"),
                ],
                default="14-11-22",
            ),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="location",
            field=models.CharField(
                choices=[
                    ("Electronic City", "Electronic City"),
                    ("Whitefield", "Whitefield"),
                    ("Jayanagar", "Jayanagar"),
                    ("Marathalli", "Marathalli"),
                ],
                default="Electronic City",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="subject",
            field=models.CharField(
                choices=[
                    ("Government", "Government"),
                    ("Corporate", "Corporate"),
                    ("Hobbyist", "Hobbyist"),
                    ("Student", "Student"),
                ],
                default="Government",
                max_length=25,
            ),
        ),
    ]
